import { poppins } from "../components/ui/fonts";

import Footer from "@/components/layout/footer/footer";
import Header from "../components/layout/header/header";

import "boxicons/css/boxicons.min.css";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";

import HeaderDataFetchWrapper from "@/components/layout/header/header-data-fetch-wrapper";
import QueryProvider from "@/store/query-client-provider";
import StoreProvider from "@/store/store-provider";
import "../components/ui/globals.css";
import AuthModal from "@/components/layout/modals/auth-modal";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import BasicDetailModal from "@/components/layout/modals/basic-detail-modal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#0177aa" />
        <meta name="robots" content="noindex, nofollow" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="application-name" content="CarOnPhone" />
        <meta name="apple-mobile-web-app-title" content="CarOnPhone" />
        <meta name="msapplication-navbutton-color" content="#0177aa" />
        <meta name="author" content="CarOnPhone" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="msapplication-starturl" content="/" />
      </head>
      <body
        className={`${poppins.className} antialiased flex flex-col bg-theme-background selection:bg-sky-100 selection:text-sky-600`}
      >
        <StoreProvider>
          <QueryProvider>
            <ToastContainer
              position="bottom-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              draggable
              theme="dark"
            />
            <HeaderDataFetchWrapper>
              <Header />
            </HeaderDataFetchWrapper>
            <AuthModal />
            <BasicDetailModal />
            <main>{children}</main>
            <Footer />
          </QueryProvider>
        </StoreProvider>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_SEARCH_PLACES_API}&libraries=places`}
          async
          defer
        ></script>
      </body>
    </html>
  );
}
